//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomAuthorization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadSource
    {
        public int SourceId { get; set; }
        public string Source { get; set; }
        public string Description { get; set; }
    }
}
